/**
 * Generates WebP derivatives and blur placeholders for raster assets in public/images.
 * Run: node scripts/optimize-images.mjs
 *
 * Output:
 *   public/images/*.webp          — compressed, width-capped variants
 *   src/data/image-assets.ts      — src + blurDataURL lookup for ProgressiveImage
 */

import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const IMAGE_DIR = path.join(process.cwd(), 'public/images');
const OUTPUT_FILE = path.join(process.cwd(), 'src/data/image-assets.ts');
const MAX_WIDTH = 1600;
const WEBP_QUALITY = 82;
const BLUR_WIDTH = 16;

const RASTER_EXT = new Set(['.png', '.jpg', '.jpeg']);

/** Case-study assets served as original PNG (no WebP derivative). */
const PNG_ONLY_BASENAME_PREFIX = 'aon-';

function isPngOnlyAsset(filePath) {
  return path.basename(filePath).startsWith(PNG_ONLY_BASENAME_PREFIX);
}

function removeWebpSibling(filePath) {
  const webpPath = filePath.replace(/\.(png|jpe?g)$/i, '.webp');
  if (fs.existsSync(webpPath)) {
    fs.unlinkSync(webpPath);
  }
}

function walkImages(dir) {
  return fs.readdirSync(dir).flatMap((entry) => {
    const fullPath = path.join(dir, entry);
    const ext = path.extname(entry).toLowerCase();
    if (fs.statSync(fullPath).isFile() && RASTER_EXT.has(ext)) {
      return [fullPath];
    }
    return [];
  });
}

async function processPngOnlyImage(filePath) {
  removeWebpSibling(filePath);

  const relative = path.relative(path.join(process.cwd(), 'public'), filePath);
  const originalSrc = `/${relative.replace(/\\/g, '/')}`;

  const blurBuffer = await sharp(filePath)
    .rotate()
    .resize(BLUR_WIDTH, null, { fit: 'inside' })
    .png({ compressionLevel: 9, palette: true })
    .toBuffer();

  const blurDataURL = `data:image/png;base64,${blurBuffer.toString('base64')}`;
  const originalSize = fs.statSync(filePath).size;

  return {
    originalSrc,
    displaySrc: originalSrc,
    blurDataURL,
    originalSize,
    outputSize: originalSize,
  };
}

async function processImage(filePath) {
  if (isPngOnlyAsset(filePath)) {
    return processPngOnlyImage(filePath);
  }

  removeWebpSibling(filePath);

  const relative = path.relative(path.join(process.cwd(), 'public'), filePath);
  const originalSrc = `/${relative.replace(/\\/g, '/')}`;
  const webpRelative = relative.replace(/\.(png|jpe?g)$/i, '.webp');
  const webpPath = path.join(process.cwd(), 'public', webpRelative);
  const webpSrc = `/${webpRelative.replace(/\\/g, '/')}`;

  const pipeline = sharp(filePath).rotate().resize(MAX_WIDTH, null, {
    withoutEnlargement: true,
  });

  await pipeline.clone().webp({ quality: WEBP_QUALITY, effort: 4 }).toFile(webpPath);

  const blurBuffer = await pipeline
    .clone()
    .resize(BLUR_WIDTH, null, { fit: 'inside' })
    .webp({ quality: 25 })
    .toBuffer();

  const blurDataURL = `data:image/webp;base64,${blurBuffer.toString('base64')}`;

  const originalSize = fs.statSync(filePath).size;
  const webpSize = fs.statSync(webpPath).size;

  return {
    originalSrc,
    displaySrc: webpSrc,
    blurDataURL,
    originalSize,
    outputSize: webpSize,
  };
}

function writeAssetMap(entries) {
  const lines = entries
    .sort((a, b) => a.originalSrc.localeCompare(b.originalSrc))
    .map(
      ({ originalSrc, displaySrc, blurDataURL }) =>
        `  ${JSON.stringify(originalSrc)}: {\n    src: ${JSON.stringify(displaySrc)},\n    blurDataURL: ${JSON.stringify(blurDataURL)},\n  },`,
    );

  const contents = `/* Auto-generated by scripts/optimize-images.mjs — do not edit manually */\n\nexport interface ImageAsset {\n  src: string;\n  blurDataURL: string;\n}\n\nexport const imageAssets: Record<string, ImageAsset> = {\n${lines.join('\n')}\n};\n\nexport function resolveImageAsset(src: string): ImageAsset | undefined {\n  return imageAssets[src];\n}\n\nexport function resolveImageSrc(src: string): string {\n  return resolveImageAsset(src)?.src ?? src;\n}\n`;

  fs.writeFileSync(OUTPUT_FILE, contents);
}

async function main() {
  const files = walkImages(IMAGE_DIR);
  const entries = [];
  let savedBytes = 0;

  for (const filePath of files) {
    const result = await processImage(filePath);
    entries.push(result);
    savedBytes += Math.max(0, result.originalSize - result.outputSize);
    const outputLabel = path.basename(result.displaySrc);
    const pngOnly = isPngOnlyAsset(filePath);
    console.log(
      `${path.basename(filePath)} → ${outputLabel}${pngOnly ? ' (PNG only)' : ''} (${formatBytes(result.originalSize)} → ${formatBytes(result.outputSize)})`,
    );
  }

  writeAssetMap(entries);
  console.log(`\nWrote ${entries.length} entries to src/data/image-assets.ts`);
  console.log(`Estimated transfer savings vs originals: ${formatBytes(savedBytes)}`);
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
