/* Auto-generated by scripts/optimize-images.mjs — do not edit manually */

export interface ImageAsset {
  src: string;
  blurDataURL: string;
}

export const imageAssets: Record<string, ImageAsset> = {
  "/images/aon-overview-dashboard.png": {
    src: "/images/aon-overview-dashboard.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABZVBMVEX////29vfs7e709fb1+vr4+fn7/Pz6+/v6+vrGxsry8/T5+/o+QE36+/r7+/v4+vr4+//7/f/x7OLv9fr57uz09vj4+fry8u/n5+n3+Pj7/Pv0+/nr6uv49/f4+Pnm7vTU4vDn7vXx8fD19vXu8PLq5tT3+/ry8e7+8vDz8OnY5fH08ujs7/Hu9Pjr7O7w8PH89vXq8fX8/f75+vrz7u39/Pzt6tnq7O1DRVL+8/H9/f3w9fnq7vDo7vPu9PXHx8v+///5+ff8/P3u7vDv8PDw7ubt7u44Okf6/Pz48vHz8vHT0dTt8vPt7u86PEn19vfAwcXh6Ozb3uLy8vL8+/zBw8eeoKXm6u07PUpub3nq6+zSx8t+ipD+/f7x8vKvtK4/QU67tru1uLz39/hAQk9AQ0/5+/vCwMRGSFX3+fi5ur7f4ePFvsJER1Lf4uVGSFQ/Qk5KTVjGx8vl5eX6+fnGx8rFxsrQ9UfnAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAn0lEQVR42mPg4Mhk42Zn5+VlL+FI4/awYohOTMri5OQsKi3LSQ8NsDdmiORJSMko4MkvzE2N8HO30GfgYoqKS2ZkLs7LDvd1M9dTZmD34QphYIiNjwkLdGbVUWFkYLWxc/X0Dw7y9nJhYlYSF2NgZ2Axs3RwcrS1NtGUFhHiZ+CQU9M2MDI11NVSl5USFeQDqVDVYGBQVJCXkZAUFmADAJQyG/5wJ7/xAAAAAElFTkSuQmCC",
  },
  "/images/aon-overview-mobile-simulation.png": {
    src: "/images/aon-overview-mobile-simulation.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABsFBMVEXf3d3V0c3o5+enqKvQzcnOzsujmp7f29rNysba2NjUzcbp6uvU09XY2Ne7uLbb29rX0s+0s7ba2NbW1dXQys21sbaWkY3EwMNwcnfg29fi4uLFwcXVzc++ub59e3rJx8SrpqKPeV53bWaLh4He4+tNUValnJ7q5+bKxslubGjAvcGqpqKhmp27r7BeTz2vrbByd3zN0dWMi4rV1dR0cW83NTHk4+ITDAnU0tDl4uHo5+nGv8J1cXB4dWu5t7/a2tqXj5Cio6uhqbLV09Gfn6V4dG/k6fSkl4zBur7IwsPCvLaPiobMy9CAf3W/tLerqa68ucFyTTuOj5GKfnKxr7OWk5KUlJeeoKejnZyBgX+XkpajoKfS0tjg4ebR0dVdV1MtHxny8fTVxbq/uLKppaZ+foLt7O+2tbnHtKhwbW+OgHvIurR3aV53dX7j5+xZTkmilYmneGhKRENUTk+hlpBoWVVAPjlvY2JIQ0CspKSuk36pn5zu7Ot6c3Hf3+WIenWBfXzn7PRpWU1SVFmupKNLSTt4cW56ZlLFvbp4dHG4trurnpiRiYO2t73Fw8agmZpX8sPTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAoUlEQVR42mNgYxbUjwxNj/HR0pAWF5HxZHBytPOPr0iti43WUROV9ehnMHQJiasvzk3LC/DTVXFr7GJwiApLySqqrSzPDLf26u1oYbCxSowoKagqLUwwde9pbm1nMLE3CwrOyM4PNNdTLGvrbGIwsnQ28E5K9rXVVBZTzeluYHC1MJZTkBLm52Xi5pFQqu5j0JYX4uNiZGXhYGfgFJBUrwEADFIoOe7cPKoAAAAASUVORK5CYII=",
  },
  "/images/aon-overview-triple-diamond.png": {
    src: "/images/aon-overview-triple-diamond.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAAA/FBMVEX////5+fn29vb6+vv6+vr7+/v9/f3+/v74+Pj8/Pz19fbx8fL39/f6+/vS09Pz8/Pt7e3y8vP29vf29fXx8fH8/f3o6Oi2trbd3d27u7vMzMz///76+fm4trTS0tLw8PD9/Pn79/a6urn+/v3//v7R0dHt69/v7uzv7+/v7/D6+vm6ubnPz8/z9fj58/b8/O/c4+P48fP9/f79/PHu4eH29/b8/Pn19fX5+vb19ffe39/39/jx8PLr6drg9Oj4+Pnt6+P8/P339vbs7e3z9/bm5+f4+vnj7tHu7e79/fzNzs7Q0dH5+fr09PXr6+z3+/zs9N/4+/z+/f3Q0NCefjdrAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAkElEQVR42h3LVRKDMBQAwBfiAQrU3d3d3V3vf5d2Ovu9YKg2ZoThiSO5RTUJGtHIVRGL9ZAQjHBQI0e/EW091QH4D0jAFN6vx35XzbniYT8MXOfL5/48zJuVdCwUCEJxvDnaajnr1v+DQynfX53Mba2VMqmPCgl2oSwWw0YnGfUKLt0MEjpGSGYzEeoRBgL+BU3tDwkJ/6AaAAAAAElFTkSuQmCC",
  },
  "/images/aon-section-01-affinity-map.png": {
    src: "/images/aon-section-01-affinity-map.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABnlBMVEX8/Pzz9PT4+Pr29vn6+vr9/fz5+fn7/Pv////s8Pb6+vz5+vz3+Pr7/P7x8fD6+v3z8/Pv7dTv7df29/Xx79zs6tbt69f089/w7dn8+Pz09eXz8Njx8e349ujz8eDy5+f19OT76vX5+OH39+bv4enw7Oz3+Pbe2Orl8Pj56+nv1tbf8/nv2/DdwtP78fHy6ff77Pb17e/t8/Dw1t7x+Prr4Nfp6vf/+vbdwdro7/Hw1uTv9PnP7/Hz7vf86/ba8PLtt7/z6N//8vv16fHu6+bx39r25vD26+v04+7t7+r9+fvh3+rs7vnc6+r54fX8/P/n7e3x3ujs8fj04+bs5fbv9vbt4fjn4uXx1tz129b04d3o6vH29//15/Pj5vPc5e/439/o6Orw5PHR0er649Ps5/jp0tbSxOv///7z5ffr3vHa6/T17/ju5fPz7+/wzbPs7evm0t3vyu/v5urs4O364On89/z69u/k7fXj2Ory8ezc6O/l09jr5u788ebs6e7jzdL97fvx6u7u7en98/jw7+/w4evp49Hw1+XC1uH/UGtEAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAoUlEQVR42mPgNLHzDo0LcnayNtVTkxFgYzCz90uvjo8OdHOx0FGS5mdn8AnJralvjokKcHQwVpbgZWDITm6qKqstD08IdjVSEONhYMhrrehsa68rifS00ZYT5WZg4MwqbSgu7Ij1stVVlxVhYmBITCuobCwK87U00FKUEuJiZUjJz8lsifCw0tdU4RAXZGZnSE3K4PB3NzfUUJWXFOZjZAEAoR4lBlKpqEsAAAAASUVORK5CYII=",
  },
  "/images/aon-section-01-persona-workshop.png": {
    src: "/images/aon-section-01-persona-workshop.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABZVBMVEX////45+f77+/+9PT84+L//f378/P98fH+9vb///799/f54+P/8PD/+fn+8fH+9fXtmZn98PD96ej+8/P22tr52dn60tL87e3TvrD97+7hj4/75OTtpaX54OD98fLOyMX9+Pjr39r53t7kjo7pm5vnp6f07e3fkZH83NvNzc399PTpqKiup6D+9/bY1deqrq/37OrSy8rxqKjssLD//v//6+vv6erkoaHPzMz0uLjejo63srX5srL17u72uLj+7u7jkZH15+Tuo6PqpaXaiorRzMu1pp395+fu5uXsqan63Nz57uyvqavusrK7ubn8397ztLTdjo795eX79/b2ycn//v7xtrbu4uGYlZTY1dP2yMj27u7d2dnb0c6Yko397e3VzsvmpKT07+/06ujj3dv59PPJy8zV09H38O6Zlpa8sKDOycaklZDnpaX85eb73t326ufd2trb19a8tay5sKe3r6v28vJ8WD5DAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAmElEQVR42mOQk1ZgMOFkYAhlYGAAUgwMivKahq4JMbEp2emFRX4WegwSOvpucRGROWnFWSWlmT7WDGpmto4eSdHhZakZBcnB3gYMkhqm9l7uLCzx+XkcQf7sugxCMtrGdp7OYVGJuSG+5qpKDDwCUio2Di5OllaBAUbqymIMrMz84iKyouwcguxawux8vCCbubiZGNkYoAAAjwcbmO+fqtkAAAAASUVORK5CYII=",
  },
  "/images/aon-section-01-strategy-presentation.png": {
    src: "/images/aon-section-01-strategy-presentation.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABO1BMVEX9/f34+fn29vb6+/v////9/v78/Pz8/f3+/v75+fny8vL4+Pj3+Pj7/Pv7+/v09fX29/fs4+T5+fr39vb09PT19PTx8fH19vbu7+/x8vL39/f5+vrm5ubz8/P6+vrt7u7y8/TQ0dHy9vb+/v/m7Ozd5ufu8/P+///s8vL99+38+vvP29799vfc2s76z9P66ev+/v38+/vz8PDP2tz2j5rs7/D66Or53d/5m6X1s7f29vn78/Pz7e75+Prj5eXn6OjN1Mnu8/TR2Nrb3tbv7/Pz9PbE2dft6+/3yc708vLw8PDI2df79ffw9fT4+/vysrT79PXu9PXv7u/a3dfw0tPeztPZw8f3+fnk5+nL19v3+vrf3NrJ19fw8e/v8/Px8/Peyc3e0NTs5eDz9PLg2sT39fXYycPZ4+Td5+XX0QRVAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAoElEQVR42mPgZ+QUFAxgYWBgY2DkZGZlZbC380wISwxk4eBjE+AX4mVn4PQSiMkIjvYx4GXn5uJmZmdgYEqNiE1JC3Vk4ZCWFBNmYjD0i48Kj0z3dtZUZmCV4BJlYLf2CEmO83Vz0FVR4OHh5GBQN7PwT3J3dTLWVlWU4WQSYWDRN7EMcrEx1VBTkpeVYhRnYNHRM7eyNdICOoRdjo+DAwCF0RZQwYZnQgAAAABJRU5ErkJggg==",
  },
  "/images/aon-section-02-scss-theme.png": {
    src: "/images/aon-section-02-scss-theme.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABYlBMVEX///8UHSJTWV3+/P38/PwBCg9YXWETHCH+/v4THSJZYWWhpKYXHSAXHyQYIikYICUbIigWICYVHyQWISYHExVVXGEQFx4LGiMVHCAXISUGExdTXGIWHyQLFRsTGyQTHSMJExUYICSBiIqBh4sEEBj4+PgWHiMGDRAUHiNYXGEEDxRcYGIVHSKEiYsACA0THiNcYmYCDROAhIb5+fl/hYn4/PwaICP09fV/gYRQV1sFEBUACA4THCB6gIT+/v/y9fb5/f38/P0EDhUTGx8SHCL6+vqAg4RQV1oCCxAKExiipKX7+/uGi4+go6Q2PkFUW14HEBVUW1+kpqfw8fH29vYbIyWDhob9//8hKCkVHiL29/j9+/sBCw/+//+Ji4ogKSkdIiUWHiIGDREcISaFh4X9/P3r6+wGCg8UHiKChYYOFBn//f307u/8+/tbXmKeoKLy7e4IERaFiYw4P0P79/gLFBohUZ9CAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAoElEQVR42mNgTIgwY2dn5+HlE+CXUbNxZijNSozk5JSXkBWXE9OycvJkKM7j4mJjM9BmkhbVtHT392PgZijJZo52MGVgYOBwZWEIYshnyClI44iyZ1E1Ng8OYfACqshlTo0Nd7Rj4GDg8GbwZWAqykyJC3OzMNJVUjax9QlkKExPimH1YNVTVxCRUjG0DmDISI4PdeHU11GUFBYUYtRgBwDYlhthhQuI3AAAAABJRU5ErkJggg==",
  },
  "/images/aon-section-02-theme-editor-output.png": {
    src: "/images/aon-section-02-theme-editor-output.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABmFBMVEX////s7vPm5+769fb59fX85ef7+/vf4ev9/f28urf27OzY2uXk5erU5unV1d3o8ffc3efW19/d6ezo7O7i5Ovx9/ji4+na4Orw9fnp6vHM0dHz+Pi4wcjr7fLd4eDx9PX9/P2us7m4ubvX3OH7/Pr//v75+fmqrrXW4PGRkprNzM3Q0dC2ur/+//7x9PqcnZ+rsLvAwMXU1Na1v8PDxsrY3d+5v8iksLbEys2lp6zJzdCstLn8/f3R09etsLZyd3yJi5S3vMa9wcmxtbtma3K4ur+/v7+doaK3u8CrtcKwsrZlaGrJycuKkJX5+firsLXW19nX19bS09Kvra2do6fZ2tuvr6+Sk5TPz9HJysr19PP8/Pzi5ei2tLLz8vK4t7a8u7mxr7O7usHLysiXlJCqoJ3f2tj9/v7c29rIv767ubZ/Yle+vbyal5azr6tTR0Cjn5wnHRmkmZXT0M67tLCglIv4+PejmI6mpKDQy8dCRknFr6G5sa3Y19WXkYvPycJOQjnUzceNg3rLvbHTzsbr6eX39/d+goPGFTFfAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAoUlEQVR42mNgZeFgY+CXUNVl8IviSGdgYOBiZmTiEVbRt3cPjE5Lzc1hEOJl5xYQ17Bz8Q6Oy8zOb2eQFhXkY5fVc/b0DWMoKmyoYFBTkBQTkbdx8w+JZCioaqpksNRUlJFSd/AIikhIqSsvbWEwt9BRljNw9AqNiefMq29sZbC2MtJWMnPyCU9M5iyubm5jMDE0NdaydQ2ITcrIqq0pKQMAAtAj9WPw128AAAAASUVORK5CYII=",
  },
  "/images/aon-section-02-theme-editor.png": {
    src: "/images/aon-section-02-theme-editor.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABaFBMVEX////8/f309vb+/Pr4+Pn6+vr29/f+///39/f4+fn08/Px7u769fT+/v74+Pf5+/vj4u76+fr49/f6+vnY4ez39vjz7Oz9/f3z8/T39fPW5OPu8fTr5eD39fHp7Orx8fHz8O/z8O71+v3x+Pn19vf4+frv8fH19PHt28n8+/v8///0/v/29fLv2s/3///5+fnjt5DmupT2/P33+fztzLPw9Pb5+Pfoxqjx7+3qz7j6+Pn08PDg6ejx8O37+vrs2MX26ef0+Pnh5u7h6efx8/Pq6/T4+Pj+/v39/Prk6vHw9PTx8/Tw6+n59PTs6vH6+/vz/f/7/v/6/v317uj1/v/z1tD5+/z1/v7mu5b259vxzsbqvJPkgjDq5+Tyx8D20MnoupKrfVvw2NH16+G1ZCPf4eN+ZlbCbCR0RzC3qpnezMlBHhDa1NL338nNxcLUzMh/X05eNyJrPypvRTNtXVB3W0zh1M1lOCAFEZANAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAmUlEQVR42mMQEuNgUlFT1tYzYmQAAxZRGUV5JQ0DQ3M7BmZmD3cGTkEpOQUtXRNLexevgJDwMAYWPhFpTX1jC1tH7+CI6IRkBk42AQlZHSsbZ5/AyJiU9FwGDm4eYUl1MyfPIIbYxIziMgZWLg5+RlU2V7+ouKTMosJ8BnZ2dl4GVlMH39D4rJLy7DyI3eJM1m7+DKlpBaU5AEK2HCFKKHu0AAAAAElFTkSuQmCC",
  },
  "/images/aon-section-02-token-architecture.png": {
    src: "/images/aon-section-02-token-architecture.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABXFBMVEX29vby8vP19fb5+fnz8/P39/f4+Pjy8/T7+/vv8PD29/j5+fr4+Pnz9PT4+Pf09vb////2+Pjy8vLy8/P5+vrx8/Px8vP39/b5+Pb5+Pn7/Pzt7e35+Pjr6+vw8PDu7+/u7e7x8fHx8vL08/Px8vH49/f19/fr7e74+fr3+Pju8fLt7u7u7u75+vvf7O74+fn29vfs6ujr9PX7+/rv8vPp6uru7/D39/jIycjo6uvl6uvw8vLp7e7x8PHr7/Ht6Or39vXu8PHp6OnBwcH9/f3z9vbx8fDv7+/m7+/p8vPU1dXW1dX6/Pz6+/vP2d7y8PLR2932+fr50tX8/f3Z2dquy9XW19fT3N+1v7f19vaUqbCbqMn69/fa6+3r8PHArp+2ssf19fS8vsJ3f5SFi4b3+fr9/PyHgZHQ1tfYtKizlIvn6+zU5um5vsCNf3br7vDAwMHAwL/s7OzY2NktuIySAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAn0lEQVR42gXBgxICARQAwFdd3V22bdu2bdvG/8+0C2o9ykMZiEYGHAARmQI2tz8ajwXsOIlKZIolBPCgiWKtmg0zSHIKWYoRIJIuMYd9bk7gwogKlRKHFE8oxDZII8OiGxCdlgtlwWC2vqzGrXyISjPT+dDkTHen63M/aheCLIvJCN359nH+vH/LST3pc1hp0OHfXocvfrwvehW218n+A1bwGygqh+IyAAAAAElFTkSuQmCC",
  },
  "/images/aon-section-03-closed-captioning.jpg": {
    src: "/images/aon-section-03-closed-captioning.jpg",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABelBMVEX////u7/D7+vr19/by8/P+/v7o6uz8/f35+vnv8PH5+vvs7e3v8fT09fXa3N3a3N7g2tfExcTv8PDHxLz4+fmvqZ/7/v/5/P7m6Oj09fTw8PDBxMf8/P2ml4X4+/20ppT2+PjJzNL5/P3k5eV/gIG+s6DFx8jw8vHX2drS086usbGhoJTEvKyppJO+tqnY29zIy8zOysTc3t3i4uPw8fFvVTdJSkva3Nzt6+rO0tSAgIDKycl5VCiPbUFWV1bJzM36/v+WiHy5ur1tVD3KxcC1ubVub2+pqam2urrRvbrDxL6DbFeimImbhXm6q46MgoI1MzHCwsDV1Nfw8PG1o4ivqKTBwsCHdmUxMDVnYGGUkpLFxMWAg3ygnpjt7e1qa2wWFBgpJymvrqyWloTPwsFJR0cpIR/b29o8OzuHg3qrq6VCQEU7OTfc29rEuaPW1tZrYVHQzcrd3d62nXc3OTmWhm6bf1xdVk06Oz7Q0NBhVEXm4drb2tjY2NgWqbw4AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAmklEQVR42mNgYOJiZxATl1NSkORlZuFgYGAQEBaVlVfV0TNUluBj5AQKaGrrmtrYOjta6GtI87ABBYydXH1C/Hw9HcyN1KS4gQIu3qGxyTGR/h72lgbqQkABr/CUrLzMxIgANzszLRFWBoaw1OyC4tK0hKhAdysVQaCKpJyKqrLykoz46CBrRX6gQG5lUWF1TX5telywiQw7AwAegB7LCrR7owAAAABJRU5ErkJggg==",
  },
  "/images/aon-section-03-mobile-sjt.jpg": {
    src: "/images/aon-section-03-mobile-sjt.jpg",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABpFBMVEUoNDnm6evs7e7r7Ov39/fs7e/y9PPa3N3w8PH4+/319/bu7+/p7O4lMTfx8vLz9fTp6usnMzkmMzj8/f2trq3O0dTp7OwlMDYnMzgYJS2VmJn6+/sZJzDBxMYZJi/o6uv09fQkMTfMztR/gYLv7+8hLTUoMjjMyssWJS4hLTTh4eDFx8j3+vrb3d4hLTYZJi5SW2FFTlHHysxUWV5ESk4bKDBEREX+//9FTlbr6+3Uz8fx8PCFhoXZ2d20saf9/v7k5OSrrJ+0tLM+Rknn5uU6Q0c7Q0n6/f7Hwrvg4eFBR0m/vr3n5+enopvCwcHn5ODDu63c3t2rqJjN0dKjloT8/v/My8phYmLS0tO3r615ZEqSkZFiX16xpJGws7Dc29mqqqunmpGsmJW8sJ78///Fu6ueoaJuVDhwY1fO0tHt6OEbGRmRb0HPzcyhjn5DQUWThYXZ2NfFyMuioZ8jIynLzM7IvKV3b2m1tLHCuaygoZexnoJdWlpyTSOWjobCspOunoaimI6zrJu3qpS7ubinoJS7t7IqJCOsqqfe29eMjHzp492t8nKXAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAoUlEQVR42mNQ07ewNLcPdefk1FHg52JjYRDXMLayC4lNTg3w0JJnZ2JlEJQzdAyKqs1Jz/Bn15XlYWRgkDTwi2ttqM9LSgn01BZgZuCVMUls6eiqqilIyww2EuNmEFJ1buOoaG5qL8mOCTeT4mNg0HQtLq2rLivPj450slEWYZDQ8/ItaqzszE0Ic7BVVxJlUDR18/Yp7M6Kj3Cx5lCRFgYAe+4mG7J7amQAAAAASUVORK5CYII=",
  },
  "/images/aon-section-03-simulation-microsite.png": {
    src: "/images/aon-section-03-simulation-microsite.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABX1BMVEX////x8vLi5OXMzMzz9fX6+/vNzc39/f33+Pj8/PzY2dnNzMzX19jFxcXJxMT29fbl5eT29vbu6+z4+fjd3d3y8vP3+Pn8/f7y8vL6+vv6+vrw8PD19Pbd3d7r6ejw8fH+/v/08vNoZG/8+/v8/fzz9Pb49/bm5eb29fTu8PDi2tTt7+///fyWj5S7ub3c2t2gm5zUzMzf4ODo6uz19fXv8PDs7vH5+fn8+/zt7u/w8fPd3t/p6urn6ezt9PepzeD69fP08O6uzt7f4uPn6OnMzM3w8/bKy8zn5+jMzc3Ozs729/b19vbLy8rAwcPOzc3h4eHOzMzMzczV1tf09vb3+fnP0dPFycr4+fnMy8vk5eXY2Njc3N3IyMnCyMrX2Njb3Nzh4+Siub23t7jj5OXAx8i6xcjGxMSSuMCjvMG5ubq6urvJx8fGxsfKysuQtr6SuL/LysrKx8ehuL3Py8pl9F2yAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAoUlEQVR42mOQl2DR1jRl9GZkCeFgDY3gYJAR1WBlV7Ry8wngCebiik9gEFc31FJQNbP18PULi47h4WVg0FfSVeY0sXTxCopiSkzJY2CQM9DTYeAwtmFjjuTjK+FmYJAUU2FnUDOyduUOTyrOTGVgEBaR5WQwZ3L2DIwryMhPY2AQFJBmZ7BwcGRjjk0vyilkYOAXkmJnsLN3cvfnTc7OygUAg0IbAmg1JBcAAAAASUVORK5CYII=",
  },
  "/images/aon-section-04-architecture-comparison.png": {
    src: "/images/aon-section-04-architecture-comparison.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABF1BMVEX////6+vr5+fn+/Pz+///7+/v3+Pj+/v78/Pz9/f3X3eD4+/vDy875+vnS4uXh5+j69fX7+PjJ1Nf9/v6pzdP6/Pz4+Pfr7+7r7u7p7+/K4eXEzdD29PPGz9K0tLnV1tj49vbCw8js7++4t7y3r7TCzM/z8vLt8vK+v8TY3N6+trv///7y8/Pz9vf3+fn5+Pj58fLP3ufy+fvh6O7x7+7o6enR0tP29/j+8fLCxMjW4uv8/f2Ut9ng5OTq8ff89vfv6uutzdLp7u/Z3+HS6fHj6OmMsdT09fe+1Njg4uL9/Pzk6uy8yM2Ptdja5ufx9/jl6Ojt8fPS7PPb4unN3N3a4uPo6ev//v79/v221NnW1daTudzs8vh7x3NvAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAjUlEQVR42mNgVZNRYAACDhYGCGCTU9FS1lC01GFgBwEGBiZpVVlNebMoUz0Wdk5OTg4GDiUJdTYT2xAHC30xkE4GAUFWNvPgUA/vcGNdUW4WDgZmTmHtGDfXMOcAG0Nxfi5GsMF2vk5+Pp7RVpJCPKxgAXcX/0jHwCAjKRE+MJ/FwN7aiz2Ck4OViZcRAJMLEVe4zvCtAAAAAElFTkSuQmCC",
  },
  "/images/aon-section-04-assessment-reports.png": {
    src: "/images/aon-section-04-assessment-reports.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABcVBMVEX9/f3////8/Pzn6ens7e3u7/L4+Pj4+Pn19fb6+vr09PX8+/zy8/P7+/v7+/z29vbu7e34+fjr8fX18/nx8PH4+fnz8/fl5PDq5u7w8vPw9Pfw8vL19vj4+/n08Ozy8vPs7/L09vfd2+vz9vji5ejp6uzw8fP19PLn6u3k5ujx8fLw7/L09fXz8fHz9Pbj5ef39/f+/f36+/vv8PH/+vzr7O33+Prm5+nr6u/x8vPu7/H29vr+/v7t7PPt7/Du6vP08/n5+vnr7e7PzuPu7/Pm5vL6+vvw7vPz8/X+/v3g4Ofb2Or0+Pvx8vXm6Oj3+frv8fL09vX//v7OxuL5+fn39fn38vv8/f3o5uvi3+rs7e7v7u7r6/H+//3z7Pf27v329/esp6LT0dLl4e3QyOSYjYTr7e3Iwrry8vL9/v3EvbeHd2bu8PPe3Nv4+/zVzcS1s7LEv7uHgoD5+vr49fz19fXIxcPKycmJblnMxr96V0vSc0mYAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAoUlEQVR42mMoLS8rrMzN4OHi4OBnZ+djYMgrqqrITk2MCmDiZJEWERBkKM4vyEpPiub2t+WW1NaVk2XILMlJS44JD/JxNpFSUtfjZYiNT0mIiwj0dbNhUJCR19Ri8AyN5A0L9nZ1YGQSF9bRMGBgcPRjD/Fyt7dmNJQQE1VWZGAws3LxYLazYGPgYGZhVeNkYGA3tnRiZTM3NRJSUeXR5wIAQ3gdwaB1Pr8AAAAASUVORK5CYII=",
  },
  "/images/aon-section-04-governance-admin.png": {
    src: "/images/aon-section-04-governance-admin.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAAA+VBMVEX+/v7w8vL5+vv19/f9/v7////6+/v8/f38/Pz7/Pz3+Pj1+Pjv8/P29/f5+fr5+vrv8PH19fbu7+/9/f3t7+/6+vv4+Pnz9PT2+Pj4+vrt8PLy9fX9/f7x8/T7+/v39/f3+Pn7+vv1+Pn09vf7/f35+fv4+fny8/T7+/3s7/D29/jy8/Pz9fbu7/Ds7e7z8/Tx8vP3+vvx8vL7+/zu8PHt8PD7+vzx9PXz7/Dw8PDx9fb5/P3v7+/39/j3+fry7u/09fbs7O7y8PD4+Pj8/P33+fn19/jn6evo7/D6+fnz8/P59fbv8fHL3+Lu8/X5+/vL3uHw8fH58/S4OqnFAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAj0lEQVR42g3IUwLDQAAFwBfubtA4qW3btnX/w7TzObh+7gFnb12Om0/crsnhe3tRslsdZTpuGQ6leD8kBvm0djBo+CGIeJ6Fw97fLFSl3W/WmIxLsFQ9yxwSlCoCIxKU6YzvKVYZSOayNC/BG3WMgm6nAMZHY0QEVeuMpRMhAkq0cFwEK1b5jK7J/xAiIpF+bQoPIVk3DmAAAAAASUVORK5CYII=",
  },
  "/images/aon-section-04-project-dashboard.png": {
    src: "/images/aon-section-04-project-dashboard.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABU1BMVEX////39vb09vf2+Pn8/Pz6+vr9/Pz7+/v4+fn5+vr3+fn7+/r29/jz9PT8/f329/f8/fz5+fr+/v6vsLX8+vr3+Pn7/f38/f7+/f349vX5+/v2+fr4+/z9/Pv//v749/fz+vr+/v329vf9/f3z+fr7+vrz8vLk7vP09fb7/Pzo8PT2+fn9/f7u8PD3+vr8+/r09PTv7u719/j7+vn1+Pjf6/H09fX2+Pjj7fL6+/v19vf4+frx9PP5+flqbHb8+/tvcXri7PHl7vKxs7drbHbq7e2trrNucHpxc3ytr7RygIP8/PugpahZa26yr7Pj4+WgqqzHx8vq7/CJjpPz8/P3+PiirK3b2Nvy8/Px9PVvcHr39/hqa3X7/fzm7O3s7/GgoqdqbHWgoadrbnejoaepqK74+PieoKb4+fjCuLxsbXf6+/r7/Puxp62LjpVsbndmZ3HmSZL/AAAACXBIWXMAABYlAAAWJQFJUiTwAAAAnUlEQVR42g3B0wLCABQA0FttbUvLtm3btm37/5/qHBA+H4jwinJW3AaXOZyO4Ha8nF77rUBQLtTak04P3t/757BbzivpbLHaHA8Axc98Hgp/fCjVW10g15vFrI+zaBEynmBjGPAyuXwqyQi6HV5fmBrDgfCEogG/02ZATGaWi00AQbfYKVadSiJmyhgKpRwwtdao10jpHASj4DSq6Ad0FBm7KCZRswAAAABJRU5ErkJggg==",
  },
  "/images/aon-section-05-prioritization-templates.png": {
    src: "/images/aon-section-05-prioritization-templates.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAABUFBMVEX////8/P719fX39/f8/Pz7+/v+/v3+/v79/f36+vr6+vv7+/z39vP5+vr6+vnz8/P8+/L+/fH49/D29vb+/Oft7e35+fn09PTw8PD39/nx8fH7+/r+/vTy8d729fbw8fT+9fH8/Pv19fT9/Of3+fXz8uDv8PTx8fL8+/v5+fPz8u3+/vX6+/z4+PDz9Pf4+Pj++ePy8uT6+//+/fP/9/bg393v7u37+u708/Hx8er08uT38+z///f7+u/+/Ob+/v/5+fj39vD5+vvz8ubf3dr09PX+/e33+Pvx8fP6+OT39/j7+/36+vXz9PX4+PL6+fr7+/T5+PP+/ff08/f8+/z5+/v39vfv+PP39/Xc8Nvn8eX68vLc8NXv8+v6+/r//u/o6/Dx6s7Y8uT5+/D5+Pb439/2/Onm6/Dy9PXm4ujt7/Lx7d3x6crw8+/w8/P6+e8E7N1eAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAm0lEQVR42h3B0xLDUBQAwNM26U1q27Zt27bN/3/rTHdBSJUQBE3DxDAcIxAAcMVSBDRHvpNjRWrlUhgUMqrB6o72vq10PVGMx4BU6m1eVn90mnFSmUoWgVxr8ZDtz23DmDSqBQ4bBGqzv7tYzQ/T9TvJDoSAJzIGm8/X/j68HH12kw4YFIqLfFx35+V24FTxARCdjggcZ45J+PsBFEsY8i2p9vkAAAAASUVORK5CYII=",
  },
  "/images/aon-section-05-triple-diamond-lifecycle.png": {
    src: "/images/aon-section-05-triple-diamond-lifecycle.png",
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAJCAMAAAAM9FwAAAAAgVBMVEX8/Pz5+fn29vfz8/P+/v77+/vy8vP////9/f36+vrp6ev19fXr6+z6+vvv7/D4+Pjz8/Tx8fHw8PHy8vL19fbu7u/t7e3p6er09PT6+/v8/Pv4+Pn8/f3r6+vt7e7s7Oz7+/zz9PX39/f5+vr9/f7w8PDp6ens7O3v8PD+/f33+PgK5W5mAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAd0lEQVR42hXLRRLDQBAEwV7sGa1kMZgZ//9Arw51yYiCm/UrCgkQ5Ig0/pgasLU0G8kwLRJeBnJOvj5qhmiJ4cFFWUUvID7vGIvu7tpoxzI/sNrP3aBEUdCV+x2AwGcPTIZeDgKQN9TqxSlptFqhOV0vpOfaNvwB58oGVer+B2wAAAAASUVORK5CYII=",
  },
  "/images/avatar-kate-baillargeon.jpg": {
    src: "/images/avatar-kate-baillargeon.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQABAABIByJQBOgBopXqcgAP7ijH2IBDVHW6ckB4GLiNGsoaxXldeew4jBJqT9luc7Hs5Evv18Uq/ng4do5rXK93xVW3Va7uCOVXPjAAA=",
  },
  "/images/avatar-meera-butler.jpg": {
    src: "/images/avatar-meera-butler.webp",
    blurDataURL: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoQABAABIByJQBOgMYOyt5yWRUN053gAP7v1016/mjwHWfG1sn1zwleZu+l52PM3apKcEtTZCYaECcTMYmPPwW9n4iQ0YIGNzQWBH3j+nvYbiHt/WsiFPBHDzxjM07EeZG5uBUN+AAAAA==",
  },
  "/images/avatar-michellanne-li.jpg": {
    src: "/images/avatar-michellanne-li.webp",
    blurDataURL: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQABAABIByJQBdgCL9AcfZ1p7AAP7tYHL6YQt68gT9V9nm+n8hn1xog0Rl/rRw6aerr3cnxzeF8ZTNENrD+kdgbUoADviu+JSgKb1AzOvMFHEmm9YMn2vgPvk5V1b5+2QAAA==",
  },
  "/images/avatar-pei-yu-shen.jpg": {
    src: "/images/avatar-pei-yu-shen.webp",
    blurDataURL: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQABAABIByJaQAAudpXl9SWAAA/uLkg9MlCTU8bv1Kg0Nh7zg+GUiHw4+9+mz8R1dQkElIMG/e4y1vFsiAAAAA",
  },
  "/images/avatar-robert-pascarella.jpg": {
    src: "/images/avatar-robert-pascarella.webp",
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQABAABIByJaQAD4csBdtyYwAA/u/GoIcQBLW3Nr5NX6swhpyV6b495wTZgW8d4jKW16yqzR+TrTgfveg7Nwr0gmM2s6bbLDoPmFaIRgAAAA==",
  },
  "/images/avatar-tom-norton.jpg": {
    src: "/images/avatar-tom-norton.webp",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQABAABIByJYgCdADAbFl1gAD+84I7WcUqL0X+ffGqXMZD8tqe7CJfeUbYUSvCc1SIw1AAAAA=",
  },
  "/images/cii-overview-data-flow.png": {
    src: "/images/cii-overview-data-flow.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkABIByJZwAAp1ec/4SqgAA/t4ALuRE2IOgr8mgxEZcOew4Nst7HbjtHZkSZlntrSGTh5+8LLhiw58uCL/IQ+cf1ddM5Xz4kJ9AAAA=",
  },
  "/images/cii-overview-master-templates.png": {
    src: "/images/cii-overview-master-templates.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkABIByJZwAAudmTrV76AD+1ewtJJ6sM+BoY19sFs3RfM33XAmldcIIggz5s0yhqSAO625USsRJVWtgNzV8LpwBNeQAAAA=",
  },
  "/images/cii-overview-signage.png": {
    src: "/images/cii-overview-signage.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJaACdADw78xi+DgAzIP8eC0wF3OZ0p4Tdk2pS/XYJIouE7q7DUBpnBdnx4pWdqc4vvs3MHFmT3s5fI7wAA==",
  },
  "/images/cii-section-01-signage-templates.png": {
    src: "/images/cii-section-01-signage-templates.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJaQAAugqltTYYQAA/mu7O+ha/EyzHS768oDd2SHItO2w89C5Tic5ZoF5L+xqCl7bawV9ioHdg+fEulQAAA==",
  },
  "/images/cii-section-01-web-banners.png": {
    src: "/images/cii-section-01-web-banners.webp",
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkABIByJaQAAuQoMJEAAMtPnraGsTDO/2caY+ld+FIovfP900Pc1eciWvoquKCT0e82OzZgAAAA",
  },
  "/images/cii-section-01-website-template.png": {
    src: "/images/cii-section-01-website-template.webp",
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkABIByJaQAAueMQ1XAAPqf7VA+Bwuw8J98V1Lhqniw4USJDRERICnmXqjoWUEAAAAA",
  },
  "/images/cii-section-02-registration-ui.png": {
    src: "/images/cii-section-02-registration-ui.webp",
    blurDataURL: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkABIByJZQCdAEUH/NQAP7tUkIXdI21U7ELu/0CGqw3HPa7RDiORej2PgAA",
  },
  "/images/cii-section-02-ux-research.png": {
    src: "/images/cii-section-02-ux-research.webp",
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAAAwAQCdASoQAAkABIByJaQAA3AA/u/5rPaD4Z/w3zRUB8RzIAA=",
  },
  "/images/cii-section-02-wireframes.png": {
    src: "/images/cii-section-02-wireframes.webp",
    blurDataURL: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoQAAkABIByJaUwAAGIAAD+79MgedZVzP7S++TVEJzlrhw9jFvYClxAAAA=",
  },
  "/images/cii-section-03-data-flow.png": {
    src: "/images/cii-section-03-data-flow.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkABIByJZwAAp1ec/4SqgAA/t4ALuRE2IOgr8mgxEZcOew4Nst7HbjtHZkSZlntrSGTh5+8LLhiw58uCL/IQ+cf1ddM5Xz4kJ9AAAA=",
  },
  "/images/cii-section-04-aabc-asia.png": {
    src: "/images/cii-section-04-aabc-asia.webp",
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkABIByJQBOgBeikhmxoAAA/PcKVOHwIq1dtY71MNUXbviSo1/vsRQAWJ9mJNdYo1AxHtp/VegQTSO3ptTbjmV1yRJeH4SzzYuOYgAAAA==",
  },
  "/images/cii-section-04-aabc-regional.png": {
    src: "/images/cii-section-04-aabc-regional.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkABIByJYwAAhz+WxQA/u5lZbmjYofVdex6rbqtlE/1I6IC7bs3IKL5OE/0HZj3zq/btE10vG/lgAA=",
  },
  "/images/cii-section-04-discovery-cross-channel.png": {
    src: "/images/cii-section-04-discovery-cross-channel.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkABIByJZQAAtpC7UeXwAD+7eCwyr7d98Ew5Lcqy5bzbEH8yQLpqGqRwOzp+ZV/RxxGBUt58AVgAAA=",
  },
  "/images/cii-section-04-dot-infographic.png": {
    src: "/images/cii-section-04-dot-infographic.webp",
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkABIByJYgCdADdJSoMAAD+6KGiqxHp4ni3arASOsFh1a9DuCegfyaOsrurzu58fgAA",
  },
  "/images/cii-section-04-wayfinding-booklet.png": {
    src: "/images/cii-section-04-wayfinding-booklet.webp",
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQAgCdASoQAAkABIByJZQC7AEeg/9fbBZPMQAA/u442v6rSka4U7p26oGb+ZSlBs9WhrR+WTvOZY7RNPxNTzrE3KvrdIhVIomrAiovuAAAAA==",
  },
  "/images/cii-section-05-entrance-built.png": {
    src: "/images/cii-section-05-entrance-built.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAkABIByJYgCdAEfoOF+rVAAAP2/WwqphjrU6Ui73KFlG+T7OmZjyFaw/DIi9aKM3QVuem6pSWvn34PgxBDrUAAAAA==",
  },
  "/images/cii-section-05-entrance-portal.png": {
    src: "/images/cii-section-05-entrance-portal.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJYwCdAEVzIJpPKAA/rQtNTSpb62cLQOtEM2bbtP4npPBKYqLVY1oiwHRH8RFDYJUNldCcW9A328PAC5QAA==",
  },
  "/images/cii-section-05-exhibit-hall.png": {
    src: "/images/cii-section-05-exhibit-hall.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJZQC7ADSFteYT4QA/NdBI8Zz9jqzW8DloWuvzp21acJA9EDMQPqPtW4x1whBC/yEymQ1PL5lEZOPUBAAAA==",
  },
  "/images/cii-section-05-exit-signage.png": {
    src: "/images/cii-section-05-exit-signage.webp",
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkABIByJQBWACLsJf9AAAD+qY1Zxvp4mFAqVEfpagv+0h1Ixf1yZMltIfAykGedAKJViAidgAAA",
  },
  "/images/cii-section-05-podium-plaque.png": {
    src: "/images/cii-section-05-podium-plaque.webp",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAkABIByJbACdAEK4EP/ZgAA/tImBpmJYkicrgOLKDWQ51fJd5ebnubwkVlYc9XiX486AAA=",
  },
  "/images/cii-section-05-registration-desk.png": {
    src: "/images/cii-section-05-registration-desk.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkABIByJQBWACKta557GwaAAP2Us8Q4070FoHvwbqnkEF6Mnt6sXsjiBYHZmZ/frE5oFmete3XtBp6nWXDKG4qJyMUqAAA=",
  },
  "/images/cii-section-05-session-marker.png": {
    src: "/images/cii-section-05-session-marker.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAwAgCdASoQAAkABIByJYgCdAEfA3f6ArhYAADLSGYtcoUvWvd5ezEuH9V/Rw9OqUsvEsXe993w0NFCQHV9FQ2AAAA=",
  },
  "/images/cii-section-05-wayfinding-signage.png": {
    src: "/images/cii-section-05-wayfinding-signage.webp",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAkABIByJZwAAubOhTNgAPKnpmixLGk4KeKS3+TVuv1r6PP3kOrolFMmwtzo/HNFSwMAAAA=",
  },
  "/images/isa-crochet.jpg": {
    src: "/images/isa-crochet.webp",
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQABAABIByJQBOgMYT2wLNXpgA/slA9kKhsO0OJh+4e6pCN9MWNFPCC+8kICLlwhdbBVanU/EjTIxsySEYCuI2h0NdcXVWdCHGweyvG865LOwWHR4Oru2SCe0AAA==",
  },
  "/images/isa-letterpress.jpg": {
    src: "/images/isa-letterpress.webp",
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQABAABIByJagCdAYv1vSIYiIKToAA/sl1KcrTbyE8vwU5EeZdoG8YcP/Ba35Tg0ZFkpiyW/0Rdrm0xwF8SIYz5N/TxiEXhDdewAbxEK4Mlda/PJByIAAA",
  },
  "/images/isa-manatee.jpg": {
    src: "/images/isa-manatee.webp",
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAQCdASoQABAABIByJbACdAYvM7YX3AAA9G8pG8/Pk7k2+/andvVtzDUGXMFtzhRdINYnQ+WMlN1gHlDy1Wb09tcx+tE22ap195wWaCo72yGne7UvLIdD/dDRxMQUqPZpJObV+9ffxgLCVp/Le8AA",
  },
  "/images/isa-profile.jpg": {
    src: "/images/isa-profile.webp",
    blurDataURL: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQABAABIByJbACdACl1ZQWM5AA/ursoPMr9SyRpRKixg+EY//xzcjpbyqqvZej5G6tSq5CfCGbWcgSmHpYnn0wjlYdYQXT5MtlktmNiK7h4LcEa6FwwDPiWbcm9jFgAAA=",
  },
  "/images/isa-wildlife-research.jpg": {
    src: "/images/isa-wildlife-research.webp",
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQABAABIByJZQC7ADMapr7wAD+8Op9yh2ZNJ3Sy1u1Wp+oFtZbDYQMu4BOuTq+qXoG21UxSLAru5Xx2XhuHIRDw6HLaAcMtLCNQZmSQk+0RrgAAAA=",
  },
  "/images/logo-amnh.jpg": {
    src: "/images/logo-amnh.webp",
    blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQABAABIByJaQAD49wamGi94AA/vEjONCr+3A/6c451LgApgja0lKhmb7usRhl3C3HIDVMVsG0w893T9b9lW8dk4Rj0n1D5zhjFUVIuAzvUAAA",
  },
  "/images/logo-aon.jpg": {
    src: "/images/logo-aon.webp",
    blurDataURL: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQABAABIByJbACdAYv1knbeMkPnAAA/ks4gmZzPbB5GyOvEymGRPGY20PXFwSaAJozucxHguMPpeP3irTyKoXT6Af/FtFaGmb8pI+/+TRzR8cy0v/gwp+/zTXvs71RpzF27AAA",
  },
  "/images/logo-cii.jpg": {
    src: "/images/logo-cii.webp",
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQABAABIByJbACdH8AGBxjimlR9VAA/vNwGtFyo6p7sPDDCWju+hZjyvpzc54ThjegwjIh8l7wvO5Ppugonx/97U/kUM+JAP6qlEexMMfa2gA9SYAAAA==",
  },
  "/images/logo-inpa.jpg": {
    src: "/images/logo-inpa.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQABAABIByJYwBTAA3GdUU05uIAAD+85hUm7nuUovSYlV0X2h3YQRFU5iJeDqXrZ5Md08eWSNY/cdbPQyHBdPP55sdy3YlwSrVawnAAAA=",
  },
  "/images/logo-korn-ferry.jpg": {
    src: "/images/logo-korn-ferry.webp",
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQABAABIByJbAAD5GtpseXM6DQYcAA/rny27QGVQl8DfAGYQIZpzT+MciX7gW88e/sfHcvmXZMcmGxTA9r0IwOm+Uz8IXfM1nK6LGbpPH/19yNvoGAAA==",
  },
  "/images/logo-ubs.jpg": {
    src: "/images/logo-ubs.webp",
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQABAABIByJaQAD5CQKDZ7g2oAAP7zgXioGjYi+Oy4WfxB1y5MRkLVvJ5HzvVU/7Cz0Cbi3U4nrCdreqa7e78DxjBzkkT9QtFd6iVFbwnvk0ZwAAA=",
  },
  "/images/logo-verizon.jpg": {
    src: "/images/logo-verizon.webp",
    blurDataURL: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQABAABIByJbACdAEPAG0snKNgAP71Z56SX8/Bja3yXWdwkddoqFSNLCVERmSIKAvEtgbh3ozEt+9fvrN8+Z8rTg/MsAAA",
  },
  "/images/project-arachnology-lab.png": {
    src: "/images/project-arachnology-lab.webp",
    blurDataURL: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABIByJYwAAueMkpQowAD4Y+3KsZyC4bmR9nvX3zgJDtriZQAPNU1HuBCe0daHrqnteq6AKsjYnEAAAA==",
  },
  "/images/project-botanical-landscape.png": {
    src: "/images/project-botanical-landscape.webp",
    blurDataURL: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABwAQCdASoQAAkABIByJQBdgA/VAAD945h1StcEDf5K1Nngts6u4uM/TIJG4WxV/OgAAA==",
  },
  "/images/project-conversational-design-system.png": {
    src: "/images/project-conversational-design-system.webp",
    blurDataURL: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABIByJaQAAlzgWT2wwAD+79fw9z9/WrcMdwBgk1kI3X0zfpsNYF+Pln4XfCUPhgsclWY1C16IzgAAAA==",
  },
  "/images/project-global-conference.jpg": {
    src: "/images/project-global-conference.webp",
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkABIByJZgCdAEN3ldZZMAA+EX/OT0nNLnWXVbUDlKpg/Ezp/yqWgUU8XEEPLbxbsLhvHqvYe52SKRzZxwYOLMoTkJNiQAAAA==",
  },
  "/images/project-immersive-assessment.jpg": {
    src: "/images/project-immersive-assessment.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkABIByJZwAAWXU6AAA/mTPBwqw2adUXP5IEr8G/ES47ZCgerN/SPt0BI78GEGloefqauRYMeBiZwO19FAUAAA=",
  },
  "/images/project-ornithology-congress.jpg": {
    src: "/images/project-ornithology-congress.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAsABIByJYgCdADFdF20DAAA/u+CivWTuInZrZ6kHw/ve4SGzmEvGTF+w82VbJTowVWCZ/T2gNspquRPfKJmHAA=",
  },
};

export function resolveImageAsset(src: string): ImageAsset | undefined {
  return imageAssets[src];
}

export function resolveImageSrc(src: string): string {
  return resolveImageAsset(src)?.src ?? src;
}
