/* Auto-generated by scripts/optimize-images.mjs — do not edit manually */

export interface ImageAsset {
  src: string;
  blurDataURL: string;
}

export const imageAssets: Record<string, ImageAsset> = {
  "/images/avatar-kate-baillargeon.jpg": {
    src: "/images/avatar-kate-baillargeon.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQABAABIByJQBOgBopXqcgAP7ijH2IBDVHW6ckB4GLiNGsoaxXldeew4jBJqT9luc7Hs5Evv18Uq/ng4do5rXK93xVW3Va7uCOVXPjAAA=",
  },
  "/images/avatar-meera-butler.jpg": {
    src: "/images/avatar-meera-butler.webp",
    blurDataURL: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoQABAABIByJQBOgMYOyt5yWRUN053gAP7v1016/mjwHWfG1sn1zwleZu+l52PM3apKcEtTZCYaECcTMYmPPwW9n4iQ0YIGNzQWBH3j+nvYbiHt/WsiFPBHDzxjM07EeZG5uBUN+AAAAA==",
  },
  "/images/avatar-michellanne-li.jpg": {
    src: "/images/avatar-michellanne-li.webp",
    blurDataURL: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQABAABIByJQBdgCL9AcfZ1p7AAP7tYHL6YQt68gT9V9nm+n8hn1xog0Rl/rRw6aerr3cnxzeF8ZTNENrD+kdgbUoADviu+JSgKb1AzOvMFHEmm9YMn2vgPvk5V1b5+2QAAA==",
  },
  "/images/avatar-pei-yu-shen.jpg": {
    src: "/images/avatar-pei-yu-shen.webp",
    blurDataURL: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQABAABIByJaQAAudpXl9SWAAA/uLkg9MlCTU8bv1Kg0Nh7zg+GUiHw4+9+mz8R1dQkElIMG/e4y1vFsiAAAAA",
  },
  "/images/avatar-robert-pascarella.jpg": {
    src: "/images/avatar-robert-pascarella.webp",
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQABAABIByJaQAD4csBdtyYwAA/u/GoIcQBLW3Nr5NX6swhpyV6b495wTZgW8d4jKW16yqzR+TrTgfveg7Nwr0gmM2s6bbLDoPmFaIRgAAAA==",
  },
  "/images/avatar-tom-norton.jpg": {
    src: "/images/avatar-tom-norton.webp",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQABAABIByJYgCdADAbFl1gAD+84I7WcUqL0X+ffGqXMZD8tqe7CJfeUbYUSvCc1SIw1AAAAA=",
  },
  "/images/cii-overview-data-flow.png": {
    src: "/images/cii-overview-data-flow.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkABIByJZwAAp1ec/4SqgAA/t4ALuRE2IOgr8mgxEZcOew4Nst7HbjtHZkSZlntrSGTh5+8LLhiw58uCL/IQ+cf1ddM5Xz4kJ9AAAA=",
  },
  "/images/cii-overview-master-templates.png": {
    src: "/images/cii-overview-master-templates.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkABIByJZwAAudmTrV76AD+1ewtJJ6sM+BoY19sFs3RfM33XAmldcIIggz5s0yhqSAO625USsRJVWtgNzV8LpwBNeQAAAA=",
  },
  "/images/cii-overview-signage.png": {
    src: "/images/cii-overview-signage.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJaACdADw78xi+DgAzIP8eC0wF3OZ0p4Tdk2pS/XYJIouE7q7DUBpnBdnx4pWdqc4vvs3MHFmT3s5fI7wAA==",
  },
  "/images/cii-section-01-signage-templates.png": {
    src: "/images/cii-section-01-signage-templates.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJaQAAugqltTYYQAA/mu7O+ha/EyzHS768oDd2SHItO2w89C5Tic5ZoF5L+xqCl7bawV9ioHdg+fEulQAAA==",
  },
  "/images/cii-section-01-web-banners.png": {
    src: "/images/cii-section-01-web-banners.webp",
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkABIByJaQAAuQoMJEAAMtPnraGsTDO/2caY+ld+FIovfP900Pc1eciWvoquKCT0e82OzZgAAAA",
  },
  "/images/cii-section-01-website-template.png": {
    src: "/images/cii-section-01-website-template.webp",
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkABIByJaQAAueMQ1XAAPqf7VA+Bwuw8J98V1Lhqniw4USJDRERICnmXqjoWUEAAAAA",
  },
  "/images/cii-section-02-registration-ui.png": {
    src: "/images/cii-section-02-registration-ui.webp",
    blurDataURL: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkABIByJZQCdAEUH/NQAP7tUkIXdI21U7ELu/0CGqw3HPa7RDiORej2PgAA",
  },
  "/images/cii-section-02-ux-research.png": {
    src: "/images/cii-section-02-ux-research.webp",
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAAAwAQCdASoQAAkABIByJaQAA3AA/u/5rPaD4Z/w3zRUB8RzIAA=",
  },
  "/images/cii-section-02-wireframes.png": {
    src: "/images/cii-section-02-wireframes.webp",
    blurDataURL: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoQAAkABIByJaUwAAGIAAD+79MgedZVzP7S++TVEJzlrhw9jFvYClxAAAA=",
  },
  "/images/cii-section-03-data-flow.png": {
    src: "/images/cii-section-03-data-flow.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAkABIByJZwAAp1ec/4SqgAA/t4ALuRE2IOgr8mgxEZcOew4Nst7HbjtHZkSZlntrSGTh5+8LLhiw58uCL/IQ+cf1ddM5Xz4kJ9AAAA=",
  },
  "/images/cii-section-04-aabc-asia.png": {
    src: "/images/cii-section-04-aabc-asia.webp",
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkABIByJQBOgBeikhmxoAAA/PcKVOHwIq1dtY71MNUXbviSo1/vsRQAWJ9mJNdYo1AxHtp/VegQTSO3ptTbjmV1yRJeH4SzzYuOYgAAAA==",
  },
  "/images/cii-section-04-aabc-regional.png": {
    src: "/images/cii-section-04-aabc-regional.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkABIByJYwAAhz+WxQA/u5lZbmjYofVdex6rbqtlE/1I6IC7bs3IKL5OE/0HZj3zq/btE10vG/lgAA=",
  },
  "/images/cii-section-04-discovery-cross-channel.png": {
    src: "/images/cii-section-04-discovery-cross-channel.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkABIByJZQAAtpC7UeXwAD+7eCwyr7d98Ew5Lcqy5bzbEH8yQLpqGqRwOzp+ZV/RxxGBUt58AVgAAA=",
  },
  "/images/cii-section-04-dot-infographic.png": {
    src: "/images/cii-section-04-dot-infographic.webp",
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkABIByJYgCdADdJSoMAAD+6KGiqxHp4ni3arASOsFh1a9DuCegfyaOsrurzu58fgAA",
  },
  "/images/cii-section-04-wayfinding-booklet.png": {
    src: "/images/cii-section-04-wayfinding-booklet.webp",
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABQAgCdASoQAAkABIByJZQC7AEeg/9fbBZPMQAA/u442v6rSka4U7p26oGb+ZSlBs9WhrR+WTvOZY7RNPxNTzrE3KvrdIhVIomrAiovuAAAAA==",
  },
  "/images/cii-section-05-entrance-built.png": {
    src: "/images/cii-section-05-entrance-built.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAkABIByJYgCdAEfoOF+rVAAAP2/WwqphjrU6Ui73KFlG+T7OmZjyFaw/DIi9aKM3QVuem6pSWvn34PgxBDrUAAAAA==",
  },
  "/images/cii-section-05-entrance-portal.png": {
    src: "/images/cii-section-05-entrance-portal.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJYwCdAEVzIJpPKAA/rQtNTSpb62cLQOtEM2bbtP4npPBKYqLVY1oiwHRH8RFDYJUNldCcW9A328PAC5QAA==",
  },
  "/images/cii-section-05-exhibit-hall.png": {
    src: "/images/cii-section-05-exhibit-hall.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABIByJZQC7ADSFteYT4QA/NdBI8Zz9jqzW8DloWuvzp21acJA9EDMQPqPtW4x1whBC/yEymQ1PL5lEZOPUBAAAA==",
  },
  "/images/cii-section-05-exit-signage.png": {
    src: "/images/cii-section-05-exit-signage.webp",
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkABIByJQBWACLsJf9AAAD+qY1Zxvp4mFAqVEfpagv+0h1Ixf1yZMltIfAykGedAKJViAidgAAA",
  },
  "/images/cii-section-05-podium-plaque.png": {
    src: "/images/cii-section-05-podium-plaque.webp",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAkABIByJbACdAEK4EP/ZgAA/tImBpmJYkicrgOLKDWQ51fJd5ebnubwkVlYc9XiX486AAA=",
  },
  "/images/cii-section-05-registration-desk.png": {
    src: "/images/cii-section-05-registration-desk.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkABIByJQBWACKta557GwaAAP2Us8Q4070FoHvwbqnkEF6Mnt6sXsjiBYHZmZ/frE5oFmete3XtBp6nWXDKG4qJyMUqAAA=",
  },
  "/images/cii-section-05-session-marker.png": {
    src: "/images/cii-section-05-session-marker.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAwAgCdASoQAAkABIByJYgCdAEfA3f6ArhYAADLSGYtcoUvWvd5ezEuH9V/Rw9OqUsvEsXe993w0NFCQHV9FQ2AAAA=",
  },
  "/images/cii-section-05-wayfinding-signage.png": {
    src: "/images/cii-section-05-wayfinding-signage.webp",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAkABIByJZwAAubOhTNgAPKnpmixLGk4KeKS3+TVuv1r6PP3kOrolFMmwtzo/HNFSwMAAAA=",
  },
  "/images/isa-crochet.jpg": {
    src: "/images/isa-crochet.webp",
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQABAABIByJQBOgMYT2wLNXpgA/slA9kKhsO0OJh+4e6pCN9MWNFPCC+8kICLlwhdbBVanU/EjTIxsySEYCuI2h0NdcXVWdCHGweyvG865LOwWHR4Oru2SCe0AAA==",
  },
  "/images/isa-letterpress.jpg": {
    src: "/images/isa-letterpress.webp",
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQABAABIByJagCdAYv1vSIYiIKToAA/sl1KcrTbyE8vwU5EeZdoG8YcP/Ba35Tg0ZFkpiyW/0Rdrm0xwF8SIYz5N/TxiEXhDdewAbxEK4Mlda/PJByIAAA",
  },
  "/images/isa-manatee.jpg": {
    src: "/images/isa-manatee.webp",
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAQCdASoQABAABIByJbACdAYvM7YX3AAA9G8pG8/Pk7k2+/andvVtzDUGXMFtzhRdINYnQ+WMlN1gHlDy1Wb09tcx+tE22ap195wWaCo72yGne7UvLIdD/dDRxMQUqPZpJObV+9ffxgLCVp/Le8AA",
  },
  "/images/isa-profile.jpg": {
    src: "/images/isa-profile.webp",
    blurDataURL: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQABAABIByJbACdACl1ZQWM5AA/ursoPMr9SyRpRKixg+EY//xzcjpbyqqvZej5G6tSq5CfCGbWcgSmHpYnn0wjlYdYQXT5MtlktmNiK7h4LcEa6FwwDPiWbcm9jFgAAA=",
  },
  "/images/isa-wildlife-research.jpg": {
    src: "/images/isa-wildlife-research.webp",
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQABAABIByJZQC7ADMapr7wAD+8Op9yh2ZNJ3Sy1u1Wp+oFtZbDYQMu4BOuTq+qXoG21UxSLAru5Xx2XhuHIRDw6HLaAcMtLCNQZmSQk+0RrgAAAA=",
  },
  "/images/logo-amnh.jpg": {
    src: "/images/logo-amnh.webp",
    blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQABAABIByJaQAD49wamGi94AA/vEjONCr+3A/6c451LgApgja0lKhmb7usRhl3C3HIDVMVsG0w893T9b9lW8dk4Rj0n1D5zhjFUVIuAzvUAAA",
  },
  "/images/logo-aon.jpg": {
    src: "/images/logo-aon.webp",
    blurDataURL: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQABAABIByJbACdAYv1knbeMkPnAAA/ks4gmZzPbB5GyOvEymGRPGY20PXFwSaAJozucxHguMPpeP3irTyKoXT6Af/FtFaGmb8pI+/+TRzR8cy0v/gwp+/zTXvs71RpzF27AAA",
  },
  "/images/logo-cii.jpg": {
    src: "/images/logo-cii.webp",
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQABAABIByJbACdH8AGBxjimlR9VAA/vNwGtFyo6p7sPDDCWju+hZjyvpzc54ThjegwjIh8l7wvO5Ppugonx/97U/kUM+JAP6qlEexMMfa2gA9SYAAAA==",
  },
  "/images/logo-inpa.jpg": {
    src: "/images/logo-inpa.webp",
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQABAABIByJYwBTAA3GdUU05uIAAD+85hUm7nuUovSYlV0X2h3YQRFU5iJeDqXrZ5Md08eWSNY/cdbPQyHBdPP55sdy3YlwSrVawnAAAA=",
  },
  "/images/logo-korn-ferry.jpg": {
    src: "/images/logo-korn-ferry.webp",
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQABAABIByJbAAD5GtpseXM6DQYcAA/rny27QGVQl8DfAGYQIZpzT+MciX7gW88e/sfHcvmXZMcmGxTA9r0IwOm+Uz8IXfM1nK6LGbpPH/19yNvoGAAA==",
  },
  "/images/logo-ubs.jpg": {
    src: "/images/logo-ubs.webp",
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQABAABIByJaQAD5CQKDZ7g2oAAP7zgXioGjYi+Oy4WfxB1y5MRkLVvJ5HzvVU/7Cz0Cbi3U4nrCdreqa7e78DxjBzkkT9QtFd6iVFbwnvk0ZwAAA=",
  },
  "/images/logo-verizon.jpg": {
    src: "/images/logo-verizon.webp",
    blurDataURL: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQABAABIByJbACdAEPAG0snKNgAP71Z56SX8/Bja3yXWdwkddoqFSNLCVERmSIKAvEtgbh3ozEt+9fvrN8+Z8rTg/MsAAA",
  },
  "/images/project-arachnology-lab.png": {
    src: "/images/project-arachnology-lab.webp",
    blurDataURL: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABIByJYwAAueMkpQowAD4Y+3KsZyC4bmR9nvX3zgJDtriZQAPNU1HuBCe0daHrqnteq6AKsjYnEAAAA==",
  },
  "/images/project-botanical-landscape.png": {
    src: "/images/project-botanical-landscape.webp",
    blurDataURL: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABwAQCdASoQAAkABIByJQBdgA/VAAD945h1StcEDf5K1Nngts6u4uM/TIJG4WxV/OgAAA==",
  },
  "/images/project-conversational-design-system.png": {
    src: "/images/project-conversational-design-system.webp",
    blurDataURL: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABIByJaQAAlzgWT2wwAD+79fw9z9/WrcMdwBgk1kI3X0zfpsNYF+Pln4XfCUPhgsclWY1C16IzgAAAA==",
  },
  "/images/project-global-conference.jpg": {
    src: "/images/project-global-conference.webp",
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkABIByJZgCdAEN3ldZZMAA+EX/OT0nNLnWXVbUDlKpg/Ezp/yqWgUU8XEEPLbxbsLhvHqvYe52SKRzZxwYOLMoTkJNiQAAAA==",
  },
  "/images/project-immersive-assessment.jpg": {
    src: "/images/project-immersive-assessment.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkABIByJZwAAWXU6AAA/mTPBwqw2adUXP5IEr8G/ES47ZCgerN/SPt0BI78GEGloefqauRYMeBiZwO19FAUAAA=",
  },
  "/images/project-ornithology-congress.jpg": {
    src: "/images/project-ornithology-congress.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAsABIByJYgCdADFdF20DAAA/u+CivWTuInZrZ6kHw/ve4SGzmEvGTF+w82VbJTowVWCZ/T2gNspquRPfKJmHAA=",
  },
};

export function resolveImageAsset(src: string): ImageAsset | undefined {
  return imageAssets[src];
}

export function resolveImageSrc(src: string): string {
  return resolveImageAsset(src)?.src ?? src;
}
